### 1-D Correlation

In [10]:
import numpy as np

data = np.array([-1, 0, -1, 0, 0, 1, -1, 1, -1, -1])

filter = np.array([-1, 1, -1])
W = len(filter)
L = len(data) - W + 1

for i in range(L):
    filtered_data = data[i:i+W]
    print(f"{'  ' * i}{filtered_data} • {filter} = {filtered_data.dot(filter)}")

[-1  0 -1] • [-1  1 -1] = 2
  [ 0 -1  0] • [-1  1 -1] = -1
    [-1  0  0] • [-1  1 -1] = 1
      [0 0 1] • [-1  1 -1] = -1
        [ 0  1 -1] • [-1  1 -1] = 2
          [ 1 -1  1] • [-1  1 -1] = -3
            [-1  1 -1] • [-1  1 -1] = 3
              [ 1 -1 -1] • [-1  1 -1] = -1


### 2-D Correlation

In [45]:
import numpy as np

width = np.arange(10, 80, 10).reshape(1, -1)
height = (np.arange(5) * 10).reshape(-1, 1)
data = width + height

filter = np.array(
    [
        [1, 2, 5],
        [-10, 2, -2],
        [5, 1, -4]
    ]
)

H, W = data.shape
window_size = 3
L_H = H - window_size + 1
L_W = W - window_size + 1

result = np.zeros((L_H, L_W))

for idx_r in range(L_H):
    for idx_c in range(L_W):
        filtered_matrix = data[idx_r:idx_r+window_size, idx_c:idx_c+window_size]
        correlation_sum_val = (filter * filtered_matrix).sum()
        result[idx_r, idx_c] = correlation_sum_val
print(result)

[[-30. -30. -30. -30. -30.]
 [-30. -30. -30. -30. -30.]
 [-30. -30. -30. -30. -30.]]


### 1-D Correlation with numpy indexing

In [149]:
import numpy as np

data = np.array([-1, 0, -1, 0, 0, 1, -1, 1, -1, -1])
filter = np.array([-1, 1, -1])
W = len(filter)
L = len(data) - W + 1

L_col_vec = np.arange(L).reshape(-1, 1)
W_row_vec = np.arange(W).reshape(1, -1)
indices = L_col_vec + W_row_vec
print(f"indices:\n{indices}\n")

data = data[np.newaxis, :]

filtered_tensor = data[:, indices].reshape(-1, *filter.shape)
print(f"filtered_tensor:\n{filtered_tensor}\n")

filtered_result = np.sum(filtered_tensor * filter, axis=filter.ndim)
print(f"filtered_result:\n{filtered_result}\n")

indices:
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]

filtered_tensor:
[[-1  0 -1]
 [ 0 -1  0]
 [-1  0  0]
 [ 0  0  1]
 [ 0  1 -1]
 [ 1 -1  1]
 [-1  1 -1]
 [ 1 -1 -1]]

filtered_result:
[ 2 -1  1 -1  2 -3  3 -1]

