# 넘파이(Numpy)

넘파이는 수치 데이터를 다루는 파이썬 패키지이다.
다차원 행렬 자료구조인 ndarray를 통해 벡터 및 행렬을 사용하는 선형 대수 계산에서 주로 사용된다.

In [2]:
# Numpy의 경우 np라는 명칭으로 임포트하는 것이 관례이다.
import numpy as np

### 1. np.array()

Numpy의 핵심은 ndarray이다. 
np.array()는 리스트, 튜플, 배열로부터 ndarray를 생성한다.

In [2]:
# 1차원 배열
vec = np.array([1, 2, 3, 4, 5])
print(vec)

[1 2 3 4 5]


2차원 배열

In [3]:
mat = np.array([[10, 20 ,30], [60, 70, 80]])
print(mat)


[[10 20 30]
 [60 70 80]]


두 배열의 타입 확인

In [5]:
print(type(vec))
print(type(mat))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


동일하게 타입이 numpy.ndarray라고 나온다.
Numpy 배열에는 축의 개수(ndim)와 크기(shape)라는 개념이 존재하는데, 배열의 크기를 정확히 숙지하는 것은 딥 러닝에서 매우 중요하다.

In [6]:
print(f"vec의 축의 갯수 : {vec.ndim}")
print(f"vec의 크기(shape) : {vec.shape}")

vec의 축의 갯수 : 1
vec의 크기(shape) : (5,)


In [7]:
print(f"mat의 축의 갯수 : {mat.ndim}")
print(f"mat의 크기(shape) : {mat.shape}")

mat의 축의 갯수 : 2
mat의 크기(shape) : (2, 3)


### 2. ndarray의 초기화

#### 1) np.zeros()

In [3]:
# 모든 값이 0인 2x3 배열 생성
zero_mat = np.zeros((2,3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


#### 2) np.ones()

In [4]:
# 모든 값이 1인 2x3 배열 생성
one_mat = np.ones((2,3))
print(one_mat)

[[1. 1. 1.]
 [1. 1. 1.]]


#### 3) np.pull()

In [5]:
# 모든 값이 특정 상수인 배열 생성
full_value = np.full((2,3), 7)
print(full_value)

[[7 7 7]
 [7 7 7]]


#### 4) np.eye()

In [6]:
# 대각선 값이 1이고 나머지 값이 0인 2차원 배열을 생성
eye_mat = np.eye(3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 5) np.random.random()

In [8]:
# 임의의 값으로 채워진 배열 생성
random_mat = np.random.random((2, 3))
print(random_mat)

[[0.41206168 0.22566979 0.33747595]
 [0.69151585 0.86198465 0.691432  ]]


### 3. np.arange()

np.arange(n)은 0부터 n-1까지의 값을 가지는 배열을 생성

In [9]:
range_vec = np.arange(10)
print(range_vec)

[0 1 2 3 4 5 6 7 8 9]


np.arange(i, j, k)는 i부터 j-1까지 k식 증가하는 배열을 생성

In [10]:
range_step_vec = np.arange(1, 10, 2)
print(range_step_vec)

[1 3 5 7 9]


### 4. np.reshape()

np.reshape()은 내부 데이터는 변경하지 않으면서 배열의 구조를 바꾼다. 단, 변경 구조와 사이즈가 맞지 많으면 ValueError이 발생한다.

In [14]:
orig_mat = np.array(np.arange(30))
print(orig_mat)
reshape_mat = orig_mat.reshape((5, 6))
print(reshape_mat)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


### 5. Numpy 슬라이싱

ndarray를 통해 만든 다차원 배열은 파이썬의 자료구조인 리스트처럼 슬라이싱 기능을 지원한다. 슬라이싱 기능을 사용하여 특정 행이나 열들의 원소들일 접근할 수 있다.

In [16]:
mat = np.array([[1, 2 ,3], [4, 5, 6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [17]:
# 첫번째 행 출력
first_row = mat[0, :]
print(first_row)

[1 2 3]


In [18]:
# 두번째 열 출력
second_column = mat[:, 1]
print(second_column)

[2 5]


### 6. Numpy 정수 인덱싱

슬라이싱을 사용하면 배열로부터 부분 배열을 추출할 수 있지만, 연속적이지 않은 원소로 배열을 만들 경우에는 슬라이싱으로는 만들 수 없다.
<br>이런 경우에는 인덱싱을 사용하여 배열을 구성할 수 있다. 인덱싱은 원하는 위치의 원소들을 뽑을 수 있다.

In [33]:
mat = np.array([[1, 2], [4, 5], [7, 8]])
print(mat)

[[1 2]
 [4 5]
 [7 8]]


특정 위치의 원소 가져오기

In [34]:
# 1행 0열의 원소
print(mat[1, 0])

4


특정 위치의 원소 두 개를 가져와 새로운 배열을 만들기

In [36]:
indexing_mat = mat[[2, 1], [0, 1]]
print(indexing_mat)

[7 5]


### 7. Numpy 연산

Numpy를 사용하면 배열간 연산을 손쉽게 수행할 수 있다. 
<br>덧셈, 뺄셈, 곱셈, 나눗셈을 위해서 연산자 (+,-,*,/)를 사용할 수 있으며 
또는 Np.add(), np.subtract(), np.multiply(), np.divide()를 사용할 수도 있다.

덧셈

In [37]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
result = x + y # np.add(x, y) 와 동일
print(result)

[5 7 9]


뺄셈

In [38]:
result = x - y # np.subtract(x, y) 와 동일
print(result)

[-3 -3 -3]


곱셈

In [39]:
result = x * y # np.mupltiply(x, y) 와 동일
print(result)

[ 4 10 18]


나눗셈

In [40]:
result = x / y
print(result)

[0.25 0.4  0.5 ]
